### ISSUE TITLE
No License file?

### ISSUE THREAD

**Issue by ssmit1986** [kubaPod/DynamicObjects#1]
I just noticed that the repository does not seem to have a license file. Is this code free to use?

**Comment by kubaPod** [comment]
Sure. The license is somewhere between 'given as is without guarantees' and 'any form of appreciation, e.g. starring the repo, is enough'.

Btw, I don't know your use case but I'd say this is a better approach [PreciseTracking](https://github.com/kubaPod/PreciseTracking). Feedback appreciated. I did not focus one either because I didn't get any.
